// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjK1fcEnGIsUzi7sXVvWkoc4C4HzB1bo',
    appId: '1:806748027575:web:0155408b0c455c9d8e2b32',
    messagingSenderId: '806748027575',
    projectId: 'emart1-f7dc7',
    authDomain: 'emart1-f7dc7.firebaseapp.com',
    databaseURL: 'https://emart1-f7dc7-default-rtdb.firebaseio.com',
    storageBucket: 'emart1-f7dc7.firebasestorage.app',
    measurementId: 'G-VBLB2W2N1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzDcLveNisKL31g5nLW6rRalaZ_945-U',
    appId: '1:806748027575:android:ff158da2281bcbd98e2b32',
    messagingSenderId: '806748027575',
    projectId: 'emart1-f7dc7',
    databaseURL: 'https://emart1-f7dc7-default-rtdb.firebaseio.com',
    storageBucket: 'emart1-f7dc7.firebasestorage.app',
  );
}
